### ISSUE TITLE
Modal Styling Updates

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#191]
**Overall:**
- [x] 2px border radius on all corners of modals; (exceptions: docked mobile on bottom corners, fullscreen modals)

**Light theme:**
- [x] body copy needs to be secondary type color blk-170  #4a4a4a

**Dark theme:**
- [x] Modal should have fill of ui-foreground-dark #2b2b2b
- [x] divider lines  blk-180  #404040
- [x] body copy needs to be secondary type color blk-060  #BFBFBF
- [x] close X icon should be blk-060  #BFBFBF

![modal update](https://user-images.githubusercontent.com/14083530/67507000-f3cbb980-f642-11e9-91d2-ae3574dd463b.png)

**Comment by macandcheese** [comment]
OK, I can update this, although the content itself is actually set by the user we can doc recommended colors for text. 👍

**Comment by bstifle** [comment]
ok got it. yeah maybe just as default?
