### ISSUE TITLE
Enhancement: Update Large component sizes

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-components#2041]
Update large component sizes use 16px font (font-size-0) and 16px icons

padding and spacing remain the same

### Affected components

- [x] Accordion
- [x] Avatar
- [x] Button (pr #2533) 
- [x] Checkbox
- [x] Chip
- [x] Combobox
- [x] Dropdown
- [x] FAB (pr #2533) 
- [x] Input
- [x] Inline Editable (pr #2533) 
- [x] Pagination
- [x] Radio Button
- [x] Radio Button Group
- [x] Radio Group (pr #2613)
- [x] Rating
- [x] Select
- [x] Split Button (pr #2533) 
- [x] Tab
- [x] Tree (pr #2803)

link to Figma designs
https://www.figma.com/file/E3SB0i5wPy7AagB7KcjF05/Calcite-Components

**Comment by caripizza** [comment]
@bstifle Tabs doesn't have a large size yet (or `scale` property for that matter). It only has 1 size right now. Are you wanting to implement the S, M, L scale feature for Tabs from issue #803 here as well? Seems like that would also allow us to close issue #1610 too?

**Comment by bstifle** [comment]
Correct!!!! I am speccing those out for you today

**Comment by bpatterson88** [comment]
Taking on avatar

**Comment by bpatterson88** [comment]
The avatar component renders at 40x40 in the codebase, but is 44x44 in Figma. Assuming the Figma version has the correct dimensions, should that be addressed as part of this issue?

**Comment by caripizza** [comment]
Adding a note that I'm taking on the tabs portion of this issue as a part of 803

**Comment by caripizza** [comment]
Taking on button from this list (from #2456)

**Comment by bpatterson88** [comment]
Taking on input

**Comment by julio8a** [comment]
Woah, nice Ben! That's a big one. Feel free to reach out if you need any help. @jcfranco was going to work on input this sprint, but go ahead and take it. Will re-assign the issue to Ben.

**Comment by julio8a** [comment]
@justinhough will work on:
* Radio button
* ration button group
* rating

**Comment by julio8a** [comment]
Looks like this one is complete, changing to installed.

**Comment by julio8a** [comment]
@macandcheese, can you verify this one?

**Comment by macandcheese** [comment]
Spot checking this looks good!
