### ISSUE TITLE
Use CSS Logical Properties, remove dir usage

### ISSUE THREAD

**Issue by caripizza** [Esri/calcite-components#2079]
**Summary**
Refactor component styles to use CSS Logical Properties and Values, perhaps via Tailwind v2 plugin
> Start using flow-relative CSS values like start/end (This would get rid of 99% of > the use for `getElementDir()`)

**Relevant Info**
- Background discussion: https://github.com/Esri/calcite-components/issues/1831#issuecomment-828786269
- MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties
- Tailwind plugins research: https://github.com/stevecochrane/tailwindcss-logical, https://github.com/stevecochrane/tailwindcss-logical#flow-relative-margins

## Components

- [x] calcite-accordion-item/calcite-accordion-item.tsx
- [x] calcite-action-pad/calcite-action-pad.tsx
- [x] calcite-alert/calcite-alert.tsx
- [x] calcite-avatar/calcite-avatar.tsx
- [x] calcite-button/calcite-button.tsx
- [x] calcite-card/calcite-card.tsx
- [x] calcite-chip/calcite-chip.tsx
- [x] calcite-color-picker/calcite-color-picker.tsx
- [x] calcite-color-picker-hex-input/calcite-color-picker-hex-input.tsx
- [x] calcite-combobox/calcite-combobox.tsx
- [x] calcite-combobox-item/calcite-combobox-item.tsx
- [x] calcite-combobox-item-group/calcite-combobox-item-group.tsx
- [x] calcite-date-picker/calcite-date-picker.tsx
- [x] calcite-date-picker-day/calcite-date-picker-day.tsx
- [x] calcite-date-picker-month/calcite-date-picker-month.tsx
- [x] calcite-date-picker-month-header/calcite-date-picker-month-header.tsx
- [x] calcite-dropdown/calcite-dropdown.tsx
- [x] calcite-dropdown-group/calcite-dropdown-group.tsx
- [x] calcite-dropdown-item/calcite-dropdown-item.tsx
- [x] calcite-fab/calcite-fab.tsx
- [x] calcite-filter/calcite-filter.tsx
- [x] calcite-icon/calcite-icon.tsx
- [x] calcite-input/calcite-input.tsx
- [x] calcite-input-date-picker/calcite-input-date-picker.tsx
- [x] calcite-input-message/calcite-input-message.tsx
- [x] calcite-label/calcite-label.tsx
- [x] calcite-link/calcite-link.tsx
- [x] calcite-modal/calcite-modal.tsx
- [x] calcite-notice/calcite-notice.tsx
- [x] calcite-pagination/calcite-pagination.tsx
- [x] calcite-panel/calcite-panel.tsx
- [x] calcite-pick-list/shared-list-render.tsx
- [x] calcite-pick-list-group/calcite-pick-list-group.tsx
- [x] calcite-popover/calcite-popover.tsx
- [x] calcite-radio-group-item/calcite-radio-group-item.tsx
- [x] calcite-rating/calcite-rating.tsx
- [x] calcite-select/calcite-select.tsx
- [x] calcite-shell-center-row/calcite-shell-center-row.tsx
- [x] ~calcite-split-button/calcite-split-button.tsx~ - has props to specify whether icon should flip in RTL contexts
- [x] calcite-stepper-item/calcite-stepper-item.tsx
- [x] calcite-switch/calcite-switch.tsx
- [x] calcite-tab-title/calcite-tab-title.tsx
- [x] calcite-tile-select/calcite-tile-select.tsx
- [x] calcite-tree-item/calcite-tree-item.tsx
- [x] functional/CalciteExpandToggle.tsx

**Comment by driskull** [comment]
I think we should bump the priority on this @jcfranco @julio8a.

We can proceed with this without upgrading to tailwind2 or using a tailwind plugin I think?

**Comment by jcfranco** [comment]
Yeah, I think we need to tackle the logical props part before 1.0.0. cc @julio8a @benelan 

https://github.com/Esri/calcite-components/issues/2868 is sort of related to this, right?

**Comment by benelan** [comment]
I agree about tackling logical props before 1.0.0 but I'm not sure the cascading scale thing is related. @jcfranco

**Comment by jcfranco** [comment]
Gotcha. Never mind then. I was under the impression that logical properties would also work through the cascade, but I can't find any examples.

@caripizza Can this be done with our current version of Tailwind? I see that `tailwindcss-logical` is compatible w/ 1.2.0+.

**Comment by driskull** [comment]
In some places, we're already using logical properties without tailwind. https://github.com/Esri/calcite-components/blob/master/src/components/calcite-radio-group-item/calcite-radio-group-item.scss#L81-L107

**Comment by jcfranco** [comment]
@driskull Thanks, that's good to know. FWIW, I want to determine if we need to split this up into another issue or if we can tackle this one as is.

**Comment by jcfranco** [comment]
Thanks for the info, @caripizza. 

In that case, let's create a separate issue to go ahead with the CSS logical properties work and repurpose this as a refactor issue. Does that sound alright? cc @benelan

**Comment by driskull** [comment]
Here are all the current instances:

@benelan @jcfranco can we prioritize this for a sprint?

It would include...

- Replacing CSS with logical css properties instead of getElementDir usage
- Removing use of rtl css utiity

```
90 results - 45 files

src/components/calcite-accordion-item/calcite-accordion-item.tsx:
   11  } from "@stencil/core";
   12: import { getElementDir, getElementProp } from "../../utils/dom";
   13  import { getKey } from "../../utils/key";

   99    render(): VNode {
  100:     const dir = getElementDir(this.el);
  101  

src/components/calcite-action-pad/calcite-action-pad.tsx:
   14  import { CalciteExpandToggle, toggleChildActionText } from "../functional/CalciteExpandToggle";
   15: import { getElementDir, focusElement, getSlotted } from "../../utils/dom";
   16  import { CSS_UTILITY } from "../../utils/resources";

  207    render(): VNode {
  208:     const rtl = getElementDir(this.el) === "rtl";
  209      const containerClasses = {

src/components/calcite-alert/calcite-alert.tsx:
   14  } from "@stencil/core";
   15: import { getElementDir, setRequestedIcon } from "../../utils/dom";
   16  import { DURATIONS, SLOTS, TEXT } from "./resources";

  130    render(): VNode {
  131:     const dir = getElementDir(this.el);
  132      const closeButton = (

src/components/calcite-avatar/calcite-avatar.tsx:
   1  import { Component, Element, h, Prop, State } from "@stencil/core";
   2: import { getElementDir } from "../../utils/dom";
   3  import { isValidHex } from "../calcite-color-picker/utils";

  68    private determineContent() {
  69:     const dir = getElementDir(this.el);
  70  

src/components/calcite-button/calcite-button.tsx:
    3  import { CSS, TEXT } from "./resources";
    4: import { closestElementCrossShadowBoundary, getElementDir } from "../../utils/dom";
    5  import { ButtonAlignment, ButtonAppearance, ButtonColor } from "./interfaces";

  150    render(): VNode {
  151:     const dir = getElementDir(this.el);
  152      const Tag = this.childElType;

src/components/calcite-card/calcite-card.tsx:
   2  import { CSS, SLOTS, TEXT } from "./resources";
   3: import { getElementDir } from "../../utils/dom";
   4  import { getKey } from "../../utils/key";

  79    render(): VNode {
  80:     const dir = getElementDir(this.el);
  81      return (

src/components/calcite-chip/calcite-chip.tsx:
    1  import { Component, h, Prop, Event, EventEmitter, Element, VNode, Method } from "@stencil/core";
    2: import { getElementDir, getSlotted } from "../../utils/dom";
    3  import { guid } from "../../utils/guid";

  112    render(): VNode {
  113:     const dir = getElementDir(this.el);
  114  

src/components/calcite-color-picker/calcite-color-picker.tsx:
   26  } from "./resources";
   27: import { focusElement, getElementDir } from "../../utils/dom";
   28  import { colorEqual, CSSColorMode, Format, normalizeHex, parseMode, SupportedMode } from "./utils";

  757      const hueLeft = hueScopeLeft ?? (colorFieldWidth * DEFAULT_COLOR.hue()) / HSV_LIMITS.h;
  758:     const elementDir = getElementDir(el);
  759      const noColor = color === null;

src/components/calcite-color-picker-hex-input/calcite-color-picker-hex-input.tsx:
   25  import { RGB } from "../calcite-color-picker/interfaces";
   26: import { focusElement, getElementDir } from "../../utils/dom";
   27  import { TEXT } from "../calcite-color-picker/resources";

  247      const hexInputValue = this.formatForInternalInput(value);
  248:     const elementDir = getElementDir(el);
  249  

src/components/calcite-combobox/calcite-combobox.tsx:
   15  import { filter } from "../../utils/filter";
   16: import { getElementDir, getElementStyleDir } from "../../utils/dom";
   17  import { debounce } from "lodash-es";

  879      const { activeChipIndex, scale, selectionMode, el } = this;
  880:     const dir = getElementDir(el);
  881      return this.selectedItems.map((item, i) => {

src/components/calcite-combobox-item/calcite-combobox-item.tsx:
   12  } from "@stencil/core";
   13: import { getElementDir, getElementProp } from "../../utils/dom";
   14  import { CSS } from "./resources";

  186      const isSingleSelect = getElementProp(this.el, "selection-mode", "multi") === "single";
  187:     const dir = getElementDir(this.el);
  188      const classes = {

src/components/calcite-combobox-item-group/calcite-combobox-item-group.tsx:
   5  import { ComboboxChildElement } from "../calcite-combobox/interfaces";
   6: import { getElementDir, getElementProp } from "../../utils/dom";
   7  import { CSS_UTILITY } from "../../utils/resources";

  61      const { el, scale } = this;
  62:     const dir = getElementDir(el);
  63      const indent = `${CSS.label}--indent-${getDepth(el)}`;

src/components/calcite-date-picker/calcite-date-picker.tsx:
   14  import { getLocaleData, DateLocaleData } from "./utils";
   15: import { getElementDir } from "../../utils/dom";
   16  import { dateFromRange, dateFromISO, dateToISO, getDaysDiff, HoverRange } from "../../utils/date";

  235  
  236:     const dir = getElementDir(this.el);
  237  

src/components/calcite-date-picker-day/calcite-date-picker-day.tsx:
   12  import { getKey } from "../../utils/key";
   13: import { getElementDir } from "../../utils/dom";
   14  import { DateLocaleData } from "../calcite-date-picker/utils";

  128        .join("");
  129:     const dir = getElementDir(this.el);
  130      return (

src/components/calcite-date-picker-month/calcite-date-picker-month.tsx:
   13  import { getKey } from "../../utils/key";
   14: import { getElementDir } from "../../utils/dom";
   15  import { DateLocaleData } from "../calcite-date-picker/utils";

  178      const nextMonDays = this.getNextMonthDays(month, year, startOfWeek);
  179:     const dir = getElementDir(this.el);
  180      const days = [

src/components/calcite-date-picker-month-header/calcite-date-picker-month-header.tsx:
   12  } from "@stencil/core";
   13: import { getElementDir } from "../../utils/dom";
   14  import {

   99    render(): VNode {
  100:     const dir = getElementDir(this.el);
  101      return (

src/components/calcite-dropdown/calcite-dropdown.tsx:
   15  import { getKey } from "../../utils/key";
   16: import { focusElement, getElementDir } from "../../utils/dom";
   17  import {

  133      const { active } = this;
  134:     const dir = getElementDir(this.el);
  135  

src/components/calcite-dropdown-group/calcite-dropdown-group.tsx:
  11  } from "@stencil/core";
  12: import { getElementDir, getElementProp } from "../../utils/dom";
  13  import { SelectionMode } from "./interfaces";

  72    render(): VNode {
  73:     const dir = getElementDir(this.el);
  74      const scale: Scale = this.scale || getElementProp(this.el, "scale", "m");

src/components/calcite-dropdown-item/calcite-dropdown-item.tsx:
   12  } from "@stencil/core";
   13: import { getElementDir, getElementProp } from "../../utils/dom";
   14  import { ItemKeyboardEvent } from "../calcite-dropdown/interfaces";

  110    render(): VNode {
  111:     const dir = getElementDir(this.el);
  112      const scale = getElementProp(this.el, "scale", "m");

src/components/calcite-fab/calcite-fab.tsx:
   4  import { CSS, ICONS } from "./resources";
   5: import { focusElement, getElementDir } from "../../utils/dom";
   6  

  96      const title = !textEnabled ? label || text || null : null;
  97:     const dir = getElementDir(el);
  98  

src/components/calcite-filter/calcite-filter.tsx:
   15  import { CSS_UTILITY } from "../../utils/resources";
   16: import { focusElement, getElementDir } from "../../utils/dom";
   17  

  207    render(): VNode {
  208:     const rtl = getElementDir(this.el) === "rtl";
  209      const { disabled } = this;

src/components/calcite-icon/calcite-icon.tsx:
   2  import { CSS } from "./resources";
   3: import { getElementDir } from "../../utils/dom";
   4  import { fetchIcon, scaleToPx } from "./utils";

  86      const { el, flipRtl, pathData, scale, textLabel } = this;
  87:     const dir = getElementDir(el);
  88      const size = scaleToPx[scale];

src/components/calcite-input/calcite-input.tsx:
   14  } from "@stencil/core";
   15: import { getElementDir, getElementProp, setRequestedIcon } from "../../utils/dom";
   16  import { getKey } from "../../utils/key";

  639    render(): VNode {
  640:     const dir = getElementDir(this.el);
  641  

src/components/calcite-input-date-picker/calcite-input-date-picker.tsx:
   16  import { getLocaleData, DateLocaleData } from "../calcite-date-picker/utils";
   17: import { getElementDir } from "../../utils/dom";
   18  import {

  305      const formattedDate = date ? date.toLocaleDateString(this.locale) : "";
  306:     const dir = getElementDir(this.el);
  307  

src/components/calcite-input-message/calcite-input-message.tsx:
   1  import { Component, Element, Host, h, Prop, VNode, Watch } from "@stencil/core";
   2: import { getElementDir, getElementProp, setRequestedIcon } from "../../utils/dom";
   3  import { Scale, Status } from "../interfaces";

  92      if (iconName) {
  93:       const dir = getElementDir(this.el);
  94  

src/components/calcite-label/calcite-label.tsx:
   1  import { Component, Element, Event, h, Prop, EventEmitter, VNode, Host } from "@stencil/core";
   2: import { getElementDir } from "../../utils/dom";
   3  import { Alignment, Scale, Status } from "../interfaces";

  82    render(): VNode {
  83:     const dir = getElementDir(this.el);
  84      return (

src/components/calcite-link/calcite-link.tsx:
   1  import { Component, Element, h, Host, Method, Prop, State, VNode, Watch } from "@stencil/core";
   2: import { focusElement, getElementDir } from "../../utils/dom";
   3  import { FlipContext } from "../interfaces";

  67    render(): VNode {
  68:     const dir = getElementDir(this.el);
  69  

src/components/calcite-modal/calcite-modal.tsx:
   18    focusElement,
   19:   getElementDir,
   20    getSlotted,

  131    render(): VNode {
  132:     const dir = getElementDir(this.el);
  133  

src/components/calcite-notice/calcite-notice.tsx:
  15  import { StatusColor, StatusIcons } from "../calcite-alert/interfaces";
  16: import { getElementDir, getSlotted, setRequestedIcon } from "../../utils/dom";
  17  import { CSS_UTILITY } from "../../utils/resources";

  97      const { el } = this;
  98:     const dir = getElementDir(el);
  99      const closeButton = (

src/components/calcite-pagination/calcite-pagination.tsx:
   11  } from "@stencil/core";
   12: import { getElementDir } from "../../utils/dom";
   13  import { Scale } from "../interfaces";

  210    render(): VNode {
  211:     const dir = getElementDir(this.el);
  212      const { total, num, start } = this;

src/components/calcite-panel/calcite-panel.tsx:
   13  import { CSS, HEADING_LEVEL, ICONS, SLOTS, TEXT } from "./resources";
   14: import { getElementDir, getElementStyleDir, getSlotted } from "../../utils/dom";
   15  import { CSS_UTILITY } from "../../utils/resources";

  428  
  429:     const rtl = getElementDir(el) === "rtl";
  430  

src/components/calcite-pick-list/shared-list-render.tsx:
   3  import { CSS, SLOTS } from "./resources";
   4: import { getElementDir } from "../../utils/dom";
   5  import { handleFilter } from "./shared-list-logic";

  40                data={dataForFilter}
  41:               dir={getElementDir(el)}
  42                disabled={loading || disabled}

src/components/calcite-pick-list-group/calcite-pick-list-group.tsx:
   4  import { HEADING_LEVEL } from "./resources";
   5: import { getElementDir, getSlotted } from "../../utils/dom";
   6  import { HeadingLevel, CalciteHeading, constrainHeadingLevel } from "../functional/CalciteHeading";

  49      const { el, groupTitle, headingLevel } = this;
  50:     const rtl = getElementDir(el) === "rtl";
  51      const hasParentItem = getSlotted(el, SLOTS.parentItem) !== null;

src/components/calcite-popover/calcite-popover.tsx:
   32  import { guid } from "../../utils/guid";
   33: import { getElementDir, queryElementRoots } from "../../utils/dom";
   34  import { CSS_UTILITY } from "../../utils/resources";

  424      const { effectiveReferenceElement, el, heading, label, open, disablePointer } = this;
  425:     const rtl = getElementDir(el) === "rtl";
  426      const displayed = effectiveReferenceElement && open;

src/components/calcite-radio-group-item/calcite-radio-group-item.tsx:
  12  } from "@stencil/core";
  13: import { getElementDir, getElementProp } from "../../utils/dom";
  14  import { RadioAppearance } from "../calcite-radio-group/interfaces";

  94      const { checked, useFallback, value } = this;
  95:     const dir = getElementDir(this.el);
  96      const scale: Scale = getElementProp(this.el, "scale", "m");

src/components/calcite-rating/calcite-rating.tsx:
   13  } from "@stencil/core";
   14: import { getElementDir } from "../../utils/dom";
   15  import { guid } from "../../utils/guid";

  179      const { intlRating, showChip, scale, count, average } = this;
  180:     const dir = getElementDir(this.el);
  181  

src/components/calcite-select/calcite-select.tsx:
   13  } from "@stencil/core";
   14: import { Direction, focusElement, getElementDir } from "../../utils/dom";
   15  import { Scale, Width } from "../interfaces";

  340    render(): VNode {
  341:     const dir = getElementDir(this.el);
  342  

src/components/calcite-shell-center-row/calcite-shell-center-row.tsx:
   3  import { Position, Scale } from "../interfaces";
   4: import { getElementDir, getSlotted } from "../../utils/dom";
   5  import { CSS_UTILITY } from "../../utils/resources";

  53      const { el } = this;
  54:     const rtl = getElementDir(el) === "rtl";
  55  

src/components/calcite-split-button/calcite-split-button.tsx:
   2  import { CSS } from "./resources";
   3: import { getElementDir } from "../../utils/dom";
   4  import { ButtonAppearance, ButtonColor, DropdownIconType } from "../calcite-button/interfaces";

  74    render(): VNode {
  75:     const dir = getElementDir(this.el);
  76      const widthClasses = {

src/components/calcite-stepper-item/calcite-stepper-item.tsx:
   12  } from "@stencil/core";
   13: import { getElementDir, getElementProp } from "../../utils/dom";
   14  import { getKey } from "../../utils/key";

  131    render(): VNode {
  132:     const dir = getElementDir(this.el);
  133      return (

src/components/calcite-switch/calcite-switch.tsx:
   13  } from "@stencil/core";
   14: import { focusElement, getElementDir } from "../../utils/dom";
   15  import { getKey } from "../../utils/key";

  196    render(): VNode {
  197:     const dir = getElementDir(this.el);
  198  

src/components/calcite-tab-title/calcite-tab-title.tsx:
   17  import { guid } from "../../utils/guid";
   18: import { getElementDir, getElementProp, getElementStyleDir } from "../../utils/dom";
   19  import { getKey } from "../../utils/key";

  133    render(): VNode {
  134:     const dir = getElementDir(this.el);
  135      const id = this.el.id || this.guid;

src/components/calcite-tile-select/calcite-tile-select.tsx:
   15  import { TileSelectType } from "./interfaces";
   16: import { getElementDir } from "../../utils/dom";
   17  import { CSS_UTILITY } from "../../utils/resources";

  256    render(): VNode {
  257:     const dir = getElementDir(this.el);
  258  

src/components/calcite-tree-item/calcite-tree-item.tsx:
   14  import { TreeSelectionMode } from "../calcite-tree/interfaces";
   15: import { nodeListToArray, getElementDir, filterDirectChildren, getSlotted } from "../../utils/dom";
   16  import { getKey } from "../../utils/key";

  131    render(): VNode {
  132:     const rtl = getElementDir(this.el) === "rtl";
  133      const showBulletPoint =

src/components/functional/CalciteExpandToggle.tsx:
   1  import { FunctionalComponent, h } from "@stencil/core";
   2: import { getElementDir, getElementStyleDir } from "../../utils/dom";
   3  import { queryActions } from "../calcite-action-bar/utils";

  88      <calcite-action
  89:       dir={getElementDir(el) === "rtl" ? "rtl" : "ltr"}
  90        icon={expanded ? expandIcon : collapseIcon}

```

**Comment by eriklharper** [comment]
Hoo boy that's a lot!

**Comment by jcfranco** [comment]
@driskull Moved to the upcoming sprint. I can help with this early next sprint. Let me know how you want to divvy it up.

**Comment by driskull** [comment]
@jcfranco you want to just start from the bottom of the list? I've started from the top.

**Comment by benelan** [comment]
This has been installed for two weeks and there have not been any reports of visual regressions or unintended changes. Closing as verified!
