### ISSUE TITLE
Epic: consistent disabled prop behavior

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#2655]
https://github.com/Esri/calcite-components/issues/2582 surfaced an issue where some of our components may not be implementing `disabled` appropriately. This epic should help us ensure all components implement this property correctly and prevent keyboard/pointer interaction with the element as well as its children (if applicable).

### Action plan

- [x] audit behavior of current components with `disabled` prop (including parent-child interactions):
- [x] fix inconsistencies (if many need to be fixed, let's split them up in PRs per component 'groups')
- [x] introduce test util to help prevent behavior inconsistencies (https://github.com/Esri/calcite-components/issues/2532)

### Questions

- Should all components have a `disabled` prop or only interactive ones? 
  - Answer: only interactive ones

### Related issues

* https://github.com/Esri/calcite-components/issues/1478
* https://github.com/Esri/calcite-components/issues/3173
* https://github.com/Esri/calcite-components/issues/3225
* https://github.com/Esri/calcite-components/issues/3226
* https://github.com/Esri/calcite-components/issues/3574
* https://github.com/Esri/calcite-components/issues/3772
* https://github.com/Esri/calcite-components/issues/2532

**Comment by jcfranco** [comment]
> Should all components have a disabled prop or only interactive ones?

@Esri/calcite-design-representatives can you chime in on this one?

**Comment by caripizza** [comment]
> Should all components have a disabled prop or only interactive ones?

IMO only interactive components should have a `disabled` prop. (ie., `disabled` prop is used to prevent interaction or communicate that an action is unavailable to the user.)

Maybe all we need to ask is does the component need to prevent interaction?

**Comment by benelan** [comment]
verified on beta.80
https://codepen.io/benesri/pen/vYpGgKz?editors=1000
