### ISSUE TITLE
Enhancement: allow customizing the animation/transition duration of components

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#3081]
### Description

Allowing users to customize the animation/transition duration will help with:

1. Accessibility – end-users can modify the duration based on https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion
2. Testing – for screenshot testing,  it is crucial to be able to set the animation/transition duration to 0 to avoid unrelated failures

For now, this issue should focus on making sure all components refer to the same CSS prop to define their animation duration both directly (setting explicit value) and indirectly (via [Tailwind util class](https://github.com/Esri/calcite-components/blob/master/tailwind.config.js#L240-L245)).

cc @caripizza 

### Acceptance Criteria 

All component animations/transitions use `--calcite-animation-timing` to determine duration.

### Relevant Info 

https://github.com/Esri/calcite-components/pull/2607/ introduced the `--calcite-animation-timing` CSS var, but this is currently not used by our components. 

#### Which Component

All of the things! ✨

##### Using explicit duration value

* [ ] [calcite-tree-item.scss](https://github.com/Esri/calcite-components/blob/d811d1c8c6fd475afd3c1cfaab31415b7a135da7/src/components/calcite-tree-item/calcite-tree-item.scss#L85)
* [ ] [calcite-tip-manager.scss](https://github.com/Esri/calcite-components/blob/d7a42e59c4d8e216d497d5bdaf73055000485e61/src/components/calcite-tip-manager/calcite-tip-manager.scss#L66)
* [ ] [calcite-split-button.scss](https://github.com/Esri/calcite-components/blob/f5270f8085b8a08955e65cdc9fd2a1a39c7e5e0b/src/components/calcite-split-button/calcite-split-button.scss#L83)
* [ ] [calcite-slider.scss](https://github.com/Esri/calcite-components/blob/13cbc7c27d3ca088877b7e7f32b8abe8d819f520/src/components/calcite-slider/calcite-slider.scss#L335)
* [ ] [calcite-slider.scss](https://github.com/Esri/calcite-components/blob/13cbc7c27d3ca088877b7e7f32b8abe8d819f520/src/components/calcite-slider/calcite-slider.scss#L327)
* [ ] [calcite-slider.scss](https://github.com/Esri/calcite-components/blob/13cbc7c27d3ca088877b7e7f32b8abe8d819f520/src/components/calcite-slider/calcite-slider.scss#L103)
* [ ] [calcite-scrim.scss](https://github.com/Esri/calcite-components/blob/4250c44f4cca8d9bb1c3495233ce3ec87dc7bc83/src/components/calcite-scrim/calcite-scrim.scss#L30)
* [ ] [calcite-radio-group-item.scss](https://github.com/Esri/calcite-components/blob/1d582f2d5e5ceba9379b64a658de9a581dbae151/src/components/calcite-radio-group-item/calcite-radio-group-item.scss#L6)
* [ ] [calcite-radio-group-item.scss](https://github.com/Esri/calcite-components/blob/1d582f2d5e5ceba9379b64a658de9a581dbae151/src/components/calcite-radio-group-item/calcite-radio-group-item.scss#L17)
* [ ] [calcite-notice.scss](https://github.com/Esri/calcite-components/blob/c698cf52cd939d1d2156745dc0047efd410a1190/src/components/calcite-notice/calcite-notice.scss#L128)
* [ ] [calcite-modal.scss](https://github.com/Esri/calcite-components/blob/a154b43e9ae9b07ec8852e3fa08e7bcea6a4b1be/src/components/calcite-modal/calcite-modal.scss#L115)
* [ ] [calcite-modal.scss](https://github.com/Esri/calcite-components/blob/a154b43e9ae9b07ec8852e3fa08e7bcea6a4b1be/src/components/calcite-modal/calcite-modal.scss#L80)
* [ ] [calcite-modal.scss](https://github.com/Esri/calcite-components/blob/a154b43e9ae9b07ec8852e3fa08e7bcea6a4b1be/src/components/calcite-modal/calcite-modal.scss#L69)
* [ ] [calcite-modal.scss](https://github.com/Esri/calcite-components/blob/a154b43e9ae9b07ec8852e3fa08e7bcea6a4b1be/src/components/calcite-modal/calcite-modal.scss#L23)
* [ ] [_animation.scss](https://github.com/Esri/calcite-components/blob/c7f70dc28a3790fb946090c0eb394aa79ca8bc64/src/assets/styles/_animation.scss#L44)
* [ ] [calcite-loader.scss](https://github.com/Esri/calcite-components/blob/13cbc7c27d3ca088877b7e7f32b8abe8d819f520/src/components/calcite-loader/calcite-loader.scss#L163)
* [ ] [_focus.scss](https://github.com/Esri/calcite-components/blob/f5270f8085b8a08955e65cdc9fd2a1a39c7e5e0b/src/assets/styles/_focus.scss#L5)
* [ ] [calcite-loader.scss](https://github.com/Esri/calcite-components/blob/13cbc7c27d3ca088877b7e7f32b8abe8d819f520/src/components/calcite-loader/calcite-loader.scss#L156)
* [ ] [calcite-loader.scss](https://github.com/Esri/calcite-components/blob/13cbc7c27d3ca088877b7e7f32b8abe8d819f520/src/components/calcite-loader/calcite-loader.scss#L149)
* [ ] [calcite-loader.scss](https://github.com/Esri/calcite-components/blob/13cbc7c27d3ca088877b7e7f32b8abe8d819f520/src/components/calcite-loader/calcite-loader.scss#L112)
* [ ] [calcite-link.scss](https://github.com/Esri/calcite-components/blob/47433942db7655b65627b557881feb879df290b8/src/components/calcite-link/calcite-link.scss#L84)
* [ ] [calcite-color-picker.scss](https://github.com/Esri/calcite-components/blob/e290c4cead95a02fa07f1deea8581e405270d51d/src/components/calcite-color-picker/calcite-color-picker.scss#L208)
* [ ] [calcite-button.scss](https://github.com/Esri/calcite-components/blob/237c8a39e5e6fd06c14222b9089643a804fa3918/src/components/calcite-button/calcite-button.scss#L233)
* [ ] [calcite-button.scss](https://github.com/Esri/calcite-components/blob/237c8a39e5e6fd06c14222b9089643a804fa3918/src/components/calcite-button/calcite-button.scss#L47)
* [ ] [calcite-alert.scss](https://github.com/Esri/calcite-components/blob/c7b2b2cde72296680c9e08cce705d2b8017b6984/src/components/calcite-alert/calcite-alert.scss#L243)
* [ ] [calcite-alert.scss](https://github.com/Esri/calcite-components/blob/c7b2b2cde72296680c9e08cce705d2b8017b6984/src/components/calcite-alert/calcite-alert.scss#L160)
* [ ] [calcite-alert.scss](https://github.com/Esri/calcite-components/blob/c7b2b2cde72296680c9e08cce705d2b8017b6984/src/components/calcite-alert/calcite-alert.scss#L104)
* [ ] [calcite-slider.scss](https://github.com/Esri/calcite-components/blob/13cbc7c27d3ca088877b7e7f32b8abe8d819f520/src/components/calcite-slider/calcite-slider.scss#L271)

##### Using Tailwind util class

* [ ] [calcite-tree-item.scss](https://github.com/Esri/calcite-components/blob/d811d1c8c6fd475afd3c1cfaab31415b7a135da7/src/components/calcite-tree-item/calcite-tree-item.scss#L198)
* [ ] [calcite-tree-item.scss](https://github.com/Esri/calcite-components/blob/d811d1c8c6fd475afd3c1cfaab31415b7a135da7/src/components/calcite-tree-item/calcite-tree-item.scss#L124)
* [ ] [calcite-tree-item.scss](https://github.com/Esri/calcite-components/blob/d811d1c8c6fd475afd3c1cfaab31415b7a135da7/src/components/calcite-tree-item/calcite-tree-item.scss#L90)
* [ ] [calcite-tab-title.scss](https://github.com/Esri/calcite-components/blob/6fa1d7b647746016e6119f16c893ec588f0f6b9f/src/components/calcite-tab-title/calcite-tab-title.scss#L158)
* [ ] [calcite-tab-title.scss](https://github.com/Esri/calcite-components/blob/6fa1d7b647746016e6119f16c893ec588f0f6b9f/src/components/calcite-tab-title/calcite-tab-title.scss#L100)
* [ ] [calcite-tab-title.scss](https://github.com/Esri/calcite-components/blob/6fa1d7b647746016e6119f16c893ec588f0f6b9f/src/components/calcite-tab-title/calcite-tab-title.scss#L84)
* [ ] [calcite-pagination.scss](https://github.com/Esri/calcite-components/blob/26656e31f04bb2b720a053c5f803bb005c80a978/src/components/calcite-pagination/calcite-pagination.scss#L78)
* [ ] [calcite-link.scss](https://github.com/Esri/calcite-components/blob/47433942db7655b65627b557881feb879df290b8/src/components/calcite-link/calcite-link.scss#L39)
* [ ] [calcite-link.scss](https://github.com/Esri/calcite-components/blob/47433942db7655b65627b557881feb879df290b8/src/components/calcite-link/calcite-link.scss#L12)
* [ ] [calcite-input.scss](https://github.com/Esri/calcite-components/blob/540f95d9bc9f61379745ab0fea50b62072cbcd34/src/components/calcite-input/calcite-input.scss#L652)
* [ ] [calcite-input.scss](https://github.com/Esri/calcite-components/blob/540f95d9bc9f61379745ab0fea50b62072cbcd34/src/components/calcite-input/calcite-input.scss#L526)
* [ ] [calcite-input.scss](https://github.com/Esri/calcite-components/blob/540f95d9bc9f61379745ab0fea50b62072cbcd34/src/components/calcite-input/calcite-input.scss#L523)
* [ ] [calcite-input.scss](https://github.com/Esri/calcite-components/blob/540f95d9bc9f61379745ab0fea50b62072cbcd34/src/components/calcite-input/calcite-input.scss#L415)
* [ ] [calcite-input.scss](https://github.com/Esri/calcite-components/blob/540f95d9bc9f61379745ab0fea50b62072cbcd34/src/components/calcite-input/calcite-input.scss#L294)
* [ ] [calcite-input.scss](https://github.com/Esri/calcite-components/blob/540f95d9bc9f61379745ab0fea50b62072cbcd34/src/components/calcite-input/calcite-input.scss#L292)
* [ ] [calcite-input.scss](https://github.com/Esri/calcite-components/blob/540f95d9bc9f61379745ab0fea50b62072cbcd34/src/components/calcite-input/calcite-input.scss#L254)
* [ ] [calcite-input-message.scss](https://github.com/Esri/calcite-components/blob/4a59f3bcee16f2174b9a6c5b2f99c851d956fe65/src/components/calcite-input-message/calcite-input-message.scss#L45)
* [ ] [calcite-input-message.scss](https://github.com/Esri/calcite-components/blob/4a59f3bcee16f2174b9a6c5b2f99c851d956fe65/src/components/calcite-input-message/calcite-input-message.scss#L32)
* [ ] [calcite-input-message.scss](https://github.com/Esri/calcite-components/blob/4a59f3bcee16f2174b9a6c5b2f99c851d956fe65/src/components/calcite-input-message/calcite-input-message.scss#L25)
* [ ] [calcite-inline-editable.scss](https://github.com/Esri/calcite-components/blob/237c8a39e5e6fd06c14222b9089643a804fa3918/src/components/calcite-inline-editable/calcite-inline-editable.scss#L32)
* [ ] [calcite-chip.scss](https://github.com/Esri/calcite-components/blob/2fc802a7e1d585a765a6881eefea573f4a8db287/src/components/calcite-chip/calcite-chip.scss#L95)

#### Example Use Case

See Description above.

### Additional Info

* Disregard [animation/transition](https://github.com/Esri/calcite-components/blob/f5270f8085b8a08955e65cdc9fd2a1a39c7e5e0b/src/assets/styles/_focus.scss#L5) duration for focus outlines as they will be phased out via https://github.com/Esri/calcite-components/issues/3345
* Disregard durations set on looping animations/transitions (e.g., loader).

**Comment by tim-white-esri** [comment]
Can we add reduced motion support to the `animation.scss` file? I've tested this locally: 
```
// because default state is opacity: 0; need to make sure that is explicitly set to 1
@media (prefers-reduced-motion: reduce) {
    .calcite-animate {
        opacity: 1;
        animation: none;
    }
}

@media (prefers-reduced-motion: no-preference) {
    .calcite-animate {
        opacity: 0;
        animation-fill-mode: both;
        animation-duration: var(--calcite-animation-timing);
    }
}
```

**Comment by caripizza** [comment]
> Can we add reduced motion support to the animation.scss file?

Sorry for the delay, @tim-white-esri! Yes and thank you for including the snippet here. I've created a new issue for that work here: #3489.

**Comment by caripizza** [comment]
@anveshmekala recapping what we discussed with Franco in our prior meet - as a part of this work, we should decrease the value of the global timing CSS var from 300ms to 150ms, so we can match the default [`$transition`](https://github.com/Esri/calcite-base/blob/master/dist/_variables.scss#L2) Sass var from calcite-base.

Then, components like calcite-action-pad, calcite-block, calcite-shell, and calcite-shell-center-row which are using the `animate-in` etc TW utility classes from the config can just have the 300ms value for this CSS var directly above the CSS style:

```scss
  /* example within a css class */
  --calcite-animation-timing: 300ms:
  @apply block animate-in rounded-sm;
```
(^ Let me know if you have questions about this approach.)

**Comment by anveshmekala** [comment]
@caripizza  i just added a issue  3491 stating this approach.

> @anveshmekala recapping what we discussed with Franco in our prior meet - as a part of this work, we should decrease the value of the global timing CSS var from 300ms to 150ms, so we can match the default [`$transition`](https://github.com/Esri/calcite-base/blob/master/dist/_variables.scss#L2) Sass var from calcite-base.
> 
> Then, components like calcite-action-pad, calcite-block, calcite-shell, and calcite-shell-center-row which are using the `animate-in` etc TW utility classes from the config can just have the 300ms value for this CSS var directly above the CSS style:
> 
> ```css-scss
>   /* example within a css class */
>   --calcite-animation-timing: 300ms:
>   @apply block animate-in rounded-sm;
> ```
> 
> (^ Let me know if you have questions about this approach.)

I added an issue [#3941](https://github.com/Esri/calcite-components/issues/3491) for this change.

**Comment by benelan** [comment]
@macandcheese can you please help me verify this design issue?

**Comment by macandcheese** [comment]
LGTM!
