### ISSUE TITLE
API consistency refactor

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#4688]
### Description

This issue aims to refactor API members for consistency. 

Individual tasks should be derived from https://github.com/Esri/calcite-components/wiki/Consistency-Audit. Boolean consistency tasks can be moved to https://github.com/Esri/calcite-components/issues/2115 if needed to split up.

The goal is to deprecate as much as possible in favor of consistent names/patterns. 

### Proposed Advantages

Consistent props, methods, event names, patterns.

### Which Component

Any component that matches audit findings.

### Relevant Info

* [x]  deprecate `'clear' | 'default'` values for `appearance` prop in the components applicable. Accepted values are `'transparent'| 'outline' | 'minimal' | 'solid'`. The prop should have no default property value.
* [x] use `open` prop for components that are not visible by default, and then appear when the prop is true. e.g. in `modal`, `popover` & `dropdown`
* [x] Use `expanded` if the component is already visible, and then grows in size when the prop is true. e.g. in `accordion-item`
* [x] use `closed` prop if the component is initially visible, and then disapears when the prop is true. Deprecate `dismissed` and `dismissible` (replace `dismissible` with `closable`). Only add `closable` if the component already has a `dismissible` prop.
* [x] replace usage of `active` prop with `open`, `expanded`, or `closed` based on the definitions above. Make sure to deprecate the `active` prop when replacing it. Ideally the `active` prop should be used to indicate focus behavior, e.g. in  `tab-title` and `action`.
* [x] deprecate `itemTitle` prop in favor of having just one prop `heading`. 
* [x] deprecate `summary `, `itemSubTitle` prop and use `description` when needed.
* [x] replace `above| below` value for `position` prop in `Tab` component with `top| bottom`. 
* [x] use `iconStart` and `iconEnd` props instead of `iconPosition` and `icon`.  Look into accordion and radio-group to transition them away from `iconPosition`.
* [x] Add `closed` prop to chip component which enables user's to hide and display chip irrespective of `closable` prop [4836](https://github.com/Esri/calcite-components/pull/4836)
* [x] Replace `disabled<Property>` with `<property>Disabled`. https://github.com/Esri/calcite-components/pull/5644#discussion_r1029836755

#### Update :

- Accordion will use existing `iconType` and `iconPosition` props to place pre-define indicator icons.
-  `action-*` components will use the `expanded` prop as the trigger element is expanding the screen space rather than
      adding a floating UI to the DOM. This includes ( action-bar, action-pad, action-menu, action-group,accordion-item)

**Comment by geospatialem** [comment]
This epic is looking fantastic! 😎  

@anveshmekala - are the epic tasks completed and ready for verification?

**Comment by anveshmekala** [comment]
Yup, these are complete and ready for verification, but the list can grow over time.

**Comment by driskull** [comment]
> action-* components will use the expanded prop as the trigger element is expanding the screen space rather than
adding a floating UI to the DOM. This includes ( action-bar, action-pad, action-menu, action-group,accordion-item)

I think i'm reconsidering this one and proposing to just use `open` or `closed` thoughts?

**Comment by driskull** [comment]
Here are some additional suggestions for consistency:

### Block

- `collapsible` => `closable`.

### Action Bar & Action Pad

- `expandable` => `closable`
- `expanded` => `open`

### Accordion Item

- `expanded` => `open`

### Action Menu

- `expanded` => `open`

### Tree Item

- `expanded` => `open`

### Alert

- `autoDismiss` => `autoClose`?
- `autoDismissDuration` => `autoCloseDuration`?

### Chip

- `dismissLabel` => `closeLabel`
- `calciteChipDismiss` => `calciteChipClose`

### Combobox

- `calciteComboboxChipDismiss` => `calciteComboboxChipClose`

### Tip

- `nonDismissible` => `close-disabled`?

### ShellPanel

- `collapsed` => `closed`

**Comment by benelan** [comment]
> ### Action Bar & Action Pad
> 
>     * `expandable` => `closable`
> 
>     * `expanded` => `open`

`closable` would only work here if the default state was `open` right? Maybe 
- `expandable` => `openable`? 

The rest of the suggestions I can get behind.

**Comment by anveshmekala** [comment]
> ### Alert
> * `autoDismiss` => `autoClose`?
> * `autoDismissDuration` => `autoCloseDuration`?
> 
> ### Chip
> * `dismissLabel` => `closeLabel`
> * `calciteChipDismiss` => `calciteChipClose`
> 
> ### Combobox
> * `calciteComboboxChipDismiss` => `calciteComboboxChipClose`
> 
> ### Tip
> * `nonDismissible` => `close-disabled`?
> 
> ### ShellPanel
> * `collapsed` => `closed`


Agree with these, the rest of them I would defer to franco.

**Comment by driskull** [comment]
chip.dismissLabel will be going away so won't modify that.

**Comment by driskull** [comment]
@geospatialem we should meet to make a call on if we want to do anything for the props that are named `expand*`, `collapse*`. We could wait for Franco to be back if we want.

**Comment by geospatialem** [comment]
> we should meet to make a call on if we want to do anything for the props that are named `expand*`, `collapse*`. We could wait for Franco to be back if we want.

@driskull Let's postpone `expand*` and `collapse*` until Franco's return. IIRC in addition to the above discussion, we've had a few discussions over the last several months on both, so would be good to get his perspective. Adding to the top of priorities for early January.

**Comment by driskull** [comment]
Ok. I made the other changes, can we verify those as part of this issue and open a new one for the expand/collapse discussion.

**Comment by geospatialem** [comment]
@driskull 👍🏻 - added the above issue, 6032, for discussing next steps on `expand*` and `collapse*` named props.

**Comment by driskull** [comment]
Here are the disabled occurrences I found.

disableFocusTrap
disablePointer
disableCloseOnSelect
disableCloseButton
disableOutsideClose
disableEscape
disableDeselect
disableFlip

**Comment by anveshmekala** [comment]
> disableFocusTrap
> disablePointer
> disableCloseOnSelect
> disableCloseButton
> disableOutsideClose
> disableEscape
> disableDeselect
> disableFlip

These need to be renamed with disabled at suffix and set to false by default. if the default value is `true`, we may need to remove `disable | disabled ` from the name.  WDYT?

**Comment by driskull** [comment]
@anveshmekala these are already false by default so its only a rename.

**Comment by driskull** [comment]
I think this issue can be marked as installed. Is that correct @anveshmekala ?

**Comment by anveshmekala** [comment]
we can mark this as installed and make sure props are consistent across the repo.

**Comment by geospatialem** [comment]
### Verification in `master`

- [x] 1. deprecate `"clear"` | `"default"` values for` appearance` prop
- [x] 2. use `open` prop for components that are not visible by default
- [x] 3. Use `expanded` if the component is already visible
- [ ] 4. use `closed` prop if the component is initially visible, and then disappears when the prop is true. Deprecate `dismissed` and `dismissible` (replace dismissible with closable). Only add `closable` if the component already has a `dismissible` prop.
- [x] 5. replace usage of `active` prop with `open`, `expanded`, or `closed` based on the definitions above.
- [x] 6. `heading` prop replacement
- [x] 7. `description` prop replacement
- [x] 8. replace `"above"`| `"below"` value for `position` prop in Tab component with `"top"`| `"bottom"`.
- [x] 9. use `iconStart` and `iconEnd` props
- [x] 10. Add `closed` prop to chip component 
- [x] 11. Replace `<property>Disabled`

### Follow up:

Related to item 4 above, @anveshmekala:
`tip` still has a [`dismissed`](https://github.com/Esri/calcite-components/blob/master/src/components/tip/tip.tsx#L50) prop, should we rename it `closeable` for consistency?

**Comment by anveshmekala** [comment]
yeah we need to rename `dismissed` to `closed` may be( `closable` is more suited for `dismissible`) . It must have slipped through. Thanks for catching it.

**Comment by geospatialem** [comment]
Will re-assign back for development to rename the `dismissed` prop to `closed`.

**Comment by geospatialem** [comment]
All components have been verified with the above. 👍🏻
