### ISSUE TITLE
Split input to type-specific components

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#5144]
### Overview
                              
`<calcite-input>` has grown in complexity and has introduced some mixed messaging in terms of the types it supports as it started mimicking the native `<input>`. This effort aims to 
split the component into simpler, focused type-specific components. 

Additionally, we've identified `<calcite-inline-editable>` as an input-like that slightly modifies input's UX and depends on users slotting an input, which is not a common pattern between existing components. 
Assimilating it into all inputs would make it simpler for developers to set up and will make input patterns more consistent.       

### Tasks

For 1.0.0, `<calcite-input>` will be split up into the following:

1. [x] `calcite-input-text` – https://github.com/Esri/calcite-components/pull/4946
2. [x] `calcite-input-number` – https://github.com/Esri/calcite-components/pull/4870
3. [ ] `calcite-input-date` – calcite-input-date-picker will be renamed
4. [ ] `calcite-input-time` – https://github.com/Esri/calcite-components/issues/2709 calcite-input-time-picker will be renamed
5. [ ] `calcite-input-color` - https://github.com/Esri/calcite-components/issues/1616, https://github.com/Esri/calcite-components/issues/1934
6. [ ] `calcite-text-area` - https://github.com/Esri/calcite-components/issues/863

Separate from ☝️, 

7. [ ] update inputs with inline-editable behavior common for all inputs (separate enhancement issue)
8. [x] decide the purpose of `calcite-input` after splitting (could be repurposed as a fallback native input if we only apply styles to a native input and drop shadow DOM) – we'll keep `calcite-input` as a way for users to use types we don't support yet and to help us gauge feedback on missing types
9. [ ] introduce an input documentation page, showcasing supported types, and common patterns (doc issue?)

### Notes

- inputs should share code through utils, functional components, additional patterns
- inline-editable behavior needs to be vetted by design per input type

cc @benelan @geospatialem

**Comment by geospatialem** [comment]
Reallocating the above into February's release.

**Comment by geospatialem** [comment]
Closing out in favor of other epics, #6566, and a newly created (internal) documentation issue.
