### ISSUE TITLE
Epic: Audit components and remove deprecations

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-components#5798]
### Purpose
Conduct an audit across components, remove deprecations, and update/remove extraneous/failing tests and stories prior to the launch of 1.0.

cc @driskull

### Plan of action for each component
1. Remove deprecations cc #3781 
2. Audit of the following:
    - Props (or any deprecated values)
    - Methods (or any deprecated arguments)
    - Events, including removal of unnecessary (`event.detail`)
    - CSS variables
    - Named slots
    - Unused utilities/resources
3. Remove them. 
4. Once deprecations are removed:
    - Remove failing/extraneous Tests
    - Update Storybook Stories
    - Update usage readme files
    - Update readme file description of component if necessary.
    - Check for any components using removed deprecations and update them.
5. Add a note with the string "deprecated" to any shared files where deprecations need to be removed after this issue has been completed.

### Sample Pull Request

When submitting a PR for a component, please refer to https://github.com/Esri/calcite-components/pull/5799 for guidance.

### Sample commit message

```
refactor(action)!: Remove deprecated properties and values. #5798
```

### Sample PR Title

Note the component and what was removed. This can be properties, events, methods, arguments, values, CSS variables, slots.

```
refactor(action)!: Remove deprecated properties and values.
```

### Sample PR Body

Note the general changes and migration options. This can span multiple lines.

```
BREAKING CHANGE: Removed the `summary` and `disablePadding` properties.

- Removed the property `summary`, use `description` instead.
- Removed the property `disablePadding`, use the CSS variable `--calcite-block-padding` instead.
```

```
BREAKING CHANGE: Removed deprecated events and properties.

- Removed the property `dismissed`, use `closed` instead.
- Removed the property `dismissible`, use `closable` instead.
- Removed the property `summary`, use `description` instead.
- Removed the property `intlBack`, use the `calcite-flow-item` component instead.
- Removed the property `showBackButton`, use `calcite-flow-item` instead.
- Removed the property `beforeBack`, use the `calcite-flow-item` component instead.
- Removed the event `calcitePanelDismiss`, use `calcitePanelClose` instead.
- Removed the event `calcitePanelDismissedChange`, use `calcitePanelClose` instead.
- Removed the event `calcitePanelBackClick`, use the `calcite-flow-item` component instead.
```

```
BREAKING CHANGE: Removed the `primary-panel` and `contextual-panel` slots.

- Removed the slot `primary-panel`, use `panel-start` instead.
- Removed the slot `contextual-panel`, use `panel-end` instead.
```

```
BREAKING CHANGE: Removed the properties `active`, `itemTitle`, `itemSubtitle`, and `icon`.

- Removed the property `active`, use `expanded` instead.
- Removed the property `itemTitle`, use `heading` instead.
- Removed the property `itemSubtitle`, use `description` instead.
- Removed the property `icon`, use `iconStart` or `iconEnd` instead.
```

### Component audit assignments and progress
- [x] `accordion` (@driskull)
- [x] `accordion-item` (@driskull)
- [x] `action` (@driskull)
- [x] `action-bar` (@driskull)
- [x] `action-group` (@driskull)
- [x] `action-menu` (@driskull)
- [x] `action-pad` (@driskull)
- [x] `alert` (@driskull)
- [x] `avatar` No changes necessary
- [x] `block` (@driskull)
- [x] `block-section` No changes necessary
- [x] `button` (@driskull)
- [x] `card` No changes necessary
- [x] `checkbox` No changes necessary
- [x] `chip` (@anveshmekala )
- [x] `color-picker` No changes necessary
- [x] `combobox` (@anveshmekala )
- [x] `combobox-item` (@anveshmekala )
- [x] `combobox-item-group` No changes necessary
- [x] `date-picker` (@eriklharper)
- [x] `dropdown` (@driskull)
- [x] `dropdown-group` (@driskull)
- [x] `dropdown-item` (@driskull)
- [x] `fab` No changes necessary
- [x] `filter` No changes necessary
- [x] `flow` (@driskull)
- [x] `flow-item` (@driskull)
- [x] `handle` (@driskull)
- [x] `icon` No changes necessary
- [x] `inline-editable` No changes necessary
- [x] `input` (@benelan)
- [x] `input-number` (@benelan)
- [x] `input-text` (@benelan)
- [x] `input-date-picker` (@eriklharper)
- [x] `input-message` (@benelan)
- [x] `input-time-picker` (@eriklharper)
- [x] `label` (@driskull)
- [x] `link` No changes necessary
- [x] `list` (@driskull)
- [x] `list-item` (@driskull)
- [x] `list-item-group` (@driskull)
- [x] `loader` (@anveshmekala )
- [x] `modal` (@anveshmekala )
- [x] `notice` (@anveshmekala )
- [x] `option` No changes necessary
- [x] `option-group` No changes necessary
- [x] `pagination` (@anveshmekala )
- [x] `panel` (@driskull)
- [x] `pick-list` No changes necessary
- [x] `pick-list-group` No changes necessary
- [x] `pick-list-item` No changes necessary
- [x] `popover` (@driskull)
- [x] `popover-manager` (@driskull)
- [x] `progress` No changes necessary
- [x] `radio-button` No changes necessary
- [x] `radio-button-group` No changes necessary
- [x] `radio-group` No changes necessary
- [x] `radio-group-item` (@driskull )
- [x] `rating` No changes necessary
- [x] `scrim` No changes necessary
- [x] `select` No changes necessary
- [x] `shell` (@driskull)
- [x] `shell-center-row`  No changes necessary. @macandcheese can we just remove this component?
- [x] `shell-panel` (@driskull)
- [x] `slider` (@driskull)
- [x] `split-button` (@driskull)
- [x] `stepper` No changes necessary
- [x] `stepper-item` (@driskull)
- [x] `switch` (@driskull)
- [x] `tab` (@driskull)
- [x] `tab-nav` No changes necessary
- [x] `tab-title` (@driskull)
- [x] `tabs` (@driskull)
- [x] `tile` No changes necessary
- [x] `tile-select` No changes necessary
- [x] `tile-select-group` No changes necessary
- [x] `time-picker` (@eriklharper)
- [x] `tip` No changes necessary
- [x] `tip-group` No changes necessary
- [x] `tip-manager` (@driskull)
- [x] `tooltip` No changes necessary
- [x] `tooltip-manager` (@driskull)
- [x] `tree` (@driskull)
- [x] `tree-item` (@driskull)
- [x] `value-list` No changes necessary
- [x] `value-list-item` No changes necessary

**Comment by driskull** [comment]
@anveshmekala I'm still seeing `chip` with a deprecatedEventPayload on `calciteChipDismiss`. Can you fix this?

Can you make sure the other PRs are removing deprecated event payloads.

**Comment by driskull** [comment]
Make sure to search the folder for anything with `"deprecated"`.

**Comment by stevenalbers** [comment]
> `radio-button-group` No changes necessary

@driskull Is this accurate? The event payload is still using `event.detail`. I'm guessing it'd use `selectedItem`, similar to `radio-group`?

**Comment by driskull** [comment]
@stevenalbers yes you're right. We need to deprecate that event detail. cc @geospatialem.

**Comment by driskull** [comment]
Looks like we missed `calciteRadioButtonGroupChange`

**Comment by geospatialem** [comment]
Added a new issue for tracking the `calciteRadioButtonChange` event payload refactor: https://github.com/Esri/calcite-components/issues/6130

**Comment by geospatialem** [comment]
Verified on `master`. ✨
