### ISSUE TITLE
Epic: remove deprecated `intl` properties  & accessible label properties.

### ISSUE THREAD

**Issue by anveshmekala** [Esri/calcite-components#5946]
### Description

Calcite supports built-in translations as part of #4961 and a new design pattern is implemented which requires the user to parse an object rather than individual properties to overwrite the default translated strings for a given locale. Once PR #5471 lands, we can deprecate existing properties that are used for overwriting translated strings and the `messageOverride` property can be used to overwrite any existing translated strings.

### Proposed Advantages

This will ensure there is only one source of truth for overriding translations & keeps the code maintainable. 

### Which Component

Here is the list of components which has properties to overwrite translations:

- [x] `action-bar` 
- [x]  `action-group`
- [x] `action-pad`
- [x] `action`
- [x] `alert`
- [x] `block-section`
- [x] `block`
- [x] `button`
- [x] `card`
- [x] `chip`
- [x] `color-picker`
- [x] `color-picker-hex-input` ( This component is `internal` )
- [x] `combobox`
- [x] `date-picker`
- [x] `filter`
- [x] `flow-item`
- [x] `inline-editable`
- [x] `input-date-picker`
- [x] `input-number`
- [x] `input-text`
- [x] `input-time-picker`
- [x] `input`
- [x] `modal`
- [x] `notice`
- [x] `pagination`
- [x] `panel`
- [x] `pick-list-item`
- [x] `popover`
- [x] `rating`
- [x] `scrim`
- [x] `time-picker`
- [x] `value-list`

Note : Not all components followed the pattern of `intl` for properties , please inspect the component thoroughly for deprecations tag

### Relevant Info

While creating PR, please make sure to follow the convention listed here in #5798 for PR title formatting and description.

**Comment by macandcheese** [comment]
@benelan @geospatialem Seeing as this will no longer be simple string properties, we will need to document how to interact with the new property. We may need a new doc type in order to let users know what strings are overridable per component.

**Comment by anveshmekala** [comment]
Users can still see what strings can be overridable considering jsdoc displays the [type](https://github.com/Esri/calcite-components/pull/5471/files#diff-2bfa0b6aded8f37b5740451e91507fcf3be1bf4b7bae26508ab8eb13284f289fR149) mentioned in components. Will this impose a challenge?

**Comment by macandcheese** [comment]
Maybe I'm misinterpreting - once the deprecated `intl-*` properties are eventually removed, there be a single `messageOverride` property per component a user can pass `{string: val, string: val, etc: etc }` to? If jsdoc can traverse and retrieve those available strings, that would be great - we'll just need to handle documenting them in another way since they won't be property/value format anymore.

**Comment by anveshmekala** [comment]
Nope, you are right about it. I was hoping jsdoc would interpret the object and I agree, we might need to handle them a bit differently and a code block in `localization` section may be explaining how to override. Thoughts?

**Comment by macandcheese** [comment]
Maybe we can introduce a @translation jsdoc tag and document per component the available strings. Similar to what we do for @slot ? That way we can pull them in automatically to each components generated API display in a new section.

**Comment by geospatialem** [comment]
Verified on `master`
