### ISSUE TITLE
[Shell / Shell Panel / Action Bar / Panel] Tracking Epic for upcoming enhancements

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#6449]
### Description

This issue serves as a catch-all epic for the proposed and upcoming enhancements to this set of layout components:

In order of need to prevent blockers or duplicate work:

- [x] #5983
- [x] **Needed for others below** #6389
- [x] **Couple with 6447** #6390 
- [x] **Couple with 6390** #6447
- [x] _Independent of above_ #6448
- [x] **Development should start after 6389 is complete* #6388 
- [x] (Needs issue, last to tackle) When slotted in top / bottom, resizable is vertical, not horizontal

Adding here for reference as its part of the design story but ultimately a separate component / implementation:

- [ ] #6391 
- [ ] Once all above complete, deprecate the Shell Center Row component when functionality exists 

### Acceptance Criteria

The above issues are completed and align with proposed design and functionality upon implementation.

Consider some of the comments from https://github.com/Esri/calcite-components/issues/2966#issuecomment-916364665, which include:

> `content-behind` is meant to work with a mapview's [view-padding](https://developers.arcgis.com/javascript/latest/sample-code/view-padding/) so that the view ui (container that holds the on-map widgets) can update without affecting the position of the map.
>
> Not moving the map as panels open/close has historically been one of the requirements of the Map Viewer.
>
> The expectation is that the app developer will update the view-padding in concert with the panels opening and closing.
>
> As it is now, Shell defaults to `content-behind="false"` and the content in the default slot behaves as a center column and responds as such.
>
> As far as `detached`, indeed it does need to work with `content-behind`. This is would be useful in Map Viewer but definitely confusing in general.

### Relevant Info

cc @brittneytewks 

### Which Component

Shell / Shell Panel / Action Bar / Sheet

### Esri team

Calcite (design)

**Comment by geospatialem** [comment]
The epic's issues have been assigned to Matt in the upcoming April release. I will own the epic to track progress as the April milestone approaches.

**Comment by geospatialem** [comment]
Migrating the epic to July, as sheet will be tackled after the May release in July.

**Comment by macandcheese** [comment]
@brittneytewks @geospatialem - I think this can be closed. All the issues have been addressed - the Sheet already has a separate issue and we can address deprecation of Shell Center Row separately.

**Comment by geospatialem** [comment]
Completed for the May milestone.
