### ISSUE TITLE
Audit: Determine internal borders for masking inputs

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-components#9413]
**monday.com sync:** #18005786328

### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

As a result of improving the `color-picker` design to include `--calcite-color-border-3`, let's first conduct an audit of what other components could benefit from masking inputs.

**Phase I**
- [ ] Conduct an audit across components to determine where the masking should be implemented
    - [ ] List out the components in the "Which component" section below.
    - [ ] Determine a dev estimate using the `estimate - #` label
- [ ] Determine if follow-up individual issues are needed to carry out the work 

**Phase II**
- [ ] Carry out the work, either via this issue, or with the individual follow-up issues

### Acceptance Criteria

Update the internal borders inside channels input to be `--calcite-color-border-3`.

### Relevant Info

Part of the https://github.com/Esri/calcite-design-system/issues/7163 epic

### Which Component

- [ ] `color-picker`
- [ ] `input-time-picker`
- [ ] `input-date-picker`
- [ ] others tbd

### Priority impact

impact - p3 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by jcfranco** [comment]
Spike findings:

I've got a prototype for a functional component that helps unify masked inputs. 

The `Which component` list seems to capture all components that will need to be updated. I've added effort estimates to each one. My recommendation is to tackle all possible with this issue in a milestone and create follow-up ones for the rest. I believe `color-picker` and `input-time-picker` can be tackled in the same milestone, but `input-date-picker` might require a bit more time.
